//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

#[allow(unused_imports)]
pub use super::system_dept::Entity as SystemDept;
#[allow(unused_imports)]
pub use super::system_dict_data::Entity as SystemDictData;
#[allow(unused_imports)]
pub use super::system_dict_type::Entity as SystemDictType;
#[allow(unused_imports)]
pub use super::system_login_log::Entity as SystemLoginLog;
#[allow(unused_imports)]
pub use super::system_mail_account::Entity as SystemMailAccount;
#[allow(unused_imports)]
pub use super::system_mail_log::Entity as SystemMailLog;
#[allow(unused_imports)]
pub use super::system_mail_template::Entity as SystemMailTemplate;
#[allow(unused_imports)]
pub use super::system_menu::Entity as SystemMenu;
#[allow(unused_imports)]
pub use super::system_notice::Entity as SystemNotice;
#[allow(unused_imports)]
pub use super::system_notify_message::Entity as SystemNotifyMessage;
#[allow(unused_imports)]
pub use super::system_notify_template::Entity as SystemNotifyTemplate;
#[allow(unused_imports)]
pub use super::system_oauth2_access_token::Entity as SystemOauth2AccessToken;
#[allow(unused_imports)]
pub use super::system_oauth2_approve::Entity as SystemOauth2Approve;
#[allow(unused_imports)]
pub use super::system_oauth2_client::Entity as SystemOauth2Client;
#[allow(unused_imports)]
pub use super::system_oauth2_code::Entity as SystemOauth2Code;
#[allow(unused_imports)]
pub use super::system_oauth2_refresh_token::Entity as SystemOauth2RefreshToken;
#[allow(unused_imports)]
pub use super::system_operate_log::Entity as SystemOperateLog;
#[allow(unused_imports)]
pub use super::system_post::Entity as SystemPost;
#[allow(unused_imports)]
pub use super::system_role::Entity as SystemRole;
#[allow(unused_imports)]
pub use super::system_role_menu::Entity as SystemRoleMenu;
#[allow(unused_imports)]
pub use super::system_sms_channel::Entity as SystemSmsChannel;
#[allow(unused_imports)]
pub use super::system_sms_code::Entity as SystemSmsCode;
#[allow(unused_imports)]
pub use super::system_sms_log::Entity as SystemSmsLog;
#[allow(unused_imports)]
pub use super::system_sms_template::Entity as SystemSmsTemplate;
#[allow(unused_imports)]
pub use super::system_social_client::Entity as SystemSocialClient;
#[allow(unused_imports)]
pub use super::system_social_user::Entity as SystemSocialUser;
#[allow(unused_imports)]
pub use super::system_social_user_bind::Entity as SystemSocialUserBind;
#[allow(unused_imports)]
pub use super::system_tenant::Entity as SystemTenant;
#[allow(unused_imports)]
pub use super::system_tenant_package::Entity as SystemTenantPackage;
#[allow(unused_imports)]
pub use super::system_user_post::Entity as SystemUserPost;
#[allow(unused_imports)]
pub use super::system_user_role::Entity as SystemUserRole;
#[allow(unused_imports)]
pub use super::system_users::Entity as SystemUsers;
