server:
  port: 8080
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: postgres
  schema: public
redis:
  host: localhost
  port: 6379
  password: 123456789
  database: 0
  expire_seconds: 60
tenant:
  enabled: true
  header_name: tenant-id
  ignore_urls:
    - /
    - /demo/api/redis/current-test-key
auth:
  method: db
  ignore_urls:
    - /
    - /demo/api/auth/login
    - /demo/api/redis/current-test-key
    - /system/admin-api/auth/login
    - /system/admin-api/auth/refresh-token
    - /system/admin-api/auth/register
    - /system/admin-api/auth/send-sms-code
sms_code:
  expire_times: 5m
