//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use daoyi_common_support::impl_common_fields_updater;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "infra_job_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i64,
    pub job_id: i64,
    pub handler_name: String,
    pub handler_param: Option<String>,
    pub execute_index: i32,
    pub begin_time: DateTime,
    pub end_time: Option<DateTime>,
    pub duration: Option<i32>,
    pub status: i32,
    pub result: Option<String>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
impl_common_fields_updater!(ActiveModel, no_tenant);
