//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub mod prelude;

pub mod sys_user;
pub mod yudao_demo01_contact;
pub mod yudao_demo02_category;
pub mod yudao_demo03_course;
pub mod yudao_demo03_grade;
pub mod yudao_demo03_student;
