//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub use super::sys_user::Entity as SysUser;
#[allow(unused_imports)]
pub use super::yudao_demo01_contact::Entity as YudaoDemo01Contact;
#[allow(unused_imports)]
pub use super::yudao_demo02_category::Entity as YudaoDemo02Category;
#[allow(unused_imports)]
pub use super::yudao_demo03_course::Entity as YudaoDemo03Course;
#[allow(unused_imports)]
pub use super::yudao_demo03_grade::Entity as YudaoDemo03Grade;
#[allow(unused_imports)]
pub use super::yudao_demo03_student::Entity as YudaoDemo03Student;
