//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use daoyi_common_support::impl_common_fields_updater;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_oauth2_refresh_token")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i64,
    pub user_id: i64,
    pub refresh_token: String,
    pub user_type: i32,
    pub client_id: String,
    pub scopes: Option<String>,
    pub expires_time: DateTime,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: i32,
    pub tenant_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
impl_common_fields_updater!(ActiveModel);
