//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use daoyi_common_support::impl_common_fields_updater;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_tenant")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i64,
    pub name: String,
    pub contact_user_id: Option<i64>,
    pub contact_name: String,
    pub contact_mobile: Option<String>,
    pub status: i32,
    pub websites: Option<String>,
    pub package_id: i64,
    pub expire_time: DateTime,
    pub account_count: i32,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
impl_common_fields_updater!(ActiveModel, no_tenant);
