//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use daoyi_common_support::impl_common_fields_updater;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "dev", table_name = "system_login_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i64,
    pub log_type: i64,
    pub trace_id: String,
    pub user_id: i64,
    pub user_type: i32,
    pub username: String,
    pub result: i32,
    pub user_ip: String,
    pub user_agent: String,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: i32,
    pub tenant_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
impl_common_fields_updater!(ActiveModel);
