[package]
name = "daoyi-module-infra"
version = "0.1.0"
edition = "2024"

[dependencies]
daoyi-common.workspace = true
anyhow.workspace = true
axum.workspace = true
tracing.workspace = true
sea-orm.workspace = true
serde.workspace = true
validator.workspace = true